typography_spectrum: 0.6282074565533549
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5390787702053785
  lightness: 0.7448207831475884
  saturation: 0.10887845675460994
  rhythmicContrast: 0.1573357949964702
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.05354571877978742
analytics:
  google: null
  facebook: null
  twitter: null
name: bendobyns
cta:
  domain: null
  bucket: null
  version: null
favicon: null
purpose: []
